image: kannonboy/atlassian-sketch-plugin:0.0.7

pipelines:
  branches:
    develop:
      - step:
          caches:
            - node
          script:
            - PIPELINES_DEPLOY_AS_LATEST=1 ./bitbucket-pipelines.sh

  tags:
    '**':
      - step:
          caches:
            - node
          script:
            - PIPELINES_DEPLOY_TAG=1 ./bitbucket-pipelines.sh

  default:
    - step:
        caches:
          - node
        script:
          - ./bitbucket-pipelines.sh
