image: node:7.10.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - PIPELINES_DEPLOY_AS_LATEST=1 ./bitbucket-pipelines.sh

  default:
    - step:
        caches:
          - node
        script:
          - ./bitbucket-pipelines.sh
