image: node:7.10.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install -g skpm@0.9.16
          - npm install
          - npm test
          - skpm build